## Broadcasting

Broadcasting is a powerful concept in NumPy that allows you to perform arithmetic operations on arrays of different shapes. It does this by automatically expanding the smaller array to match the shape of the larger array, so that they have compatible shapes.

Broadcasting rules in NumPy are as follows:

1. If the arrays have different numbers of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.

2. If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.

3. If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [22]:
import numpy as np

# Create a vector of 9 elements
vector = np.arange(9)

# Reshape the vector into a 3x3 matrix
matrix = vector.reshape(3, 3)

# Repeat the matrix 3 times along the columns
repeatedMatrix = np.tile(matrix, (3, 1))

# brroadcast the matrix with the vector
vectorTransposed = np.reshape(vector, (9, 1))
broadcastedMatrix = repeatedMatrix * vectorTransposed

print(vector)
print()

print(matrix)
print()

print(repeatedMatrix)
print()
print(broadcastedMatrix)

[0 1 2 3 4 5 6 7 8]

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]
 [0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 0  0  0]
 [ 3  4  5]
 [12 14 16]
 [ 0  3  6]
 [12 16 20]
 [30 35 40]
 [ 0  6 12]
 [21 28 35]
 [48 56 64]]
